### ISSUE TITLE
Going Public

### ISSUE THREAD

**Issue by akleb** [mdolab/prefoil#37]
# Description of feature
Interested in cleaning this repo up enough to go public with it. 

- What sort of things should be completed before this happens? 
- Are there more features that we need to add? 
- Does more extensive testing for certain features need to be completed? 

I am making this issue to provide a place to document changes we would like to make before this repo can go public. 

@mdolab/pyfoil_maintainers 

TODO:
- [x] check the license file and update as needed
- [x] rename the repo
- [ ] make this repo public
- [ ] move Azure to public
- [ ] add codecov
- [ ] remove RTD and remake project (and set visibility to public)
- [ ] update README badge to reflect new URLs
- [ ] add this repo to MACH-Aero README?
- [ ] add this repo to buildbot?

**Comment by nwu63** [comment]
@akleb is there anything missing from this list or can we close this issue?
